imports:
    - { resource: config_test.yml }

security:
    encoders:
        SwitchUserStatelessBundle\Tests\UserBundle\Entity\User: plaintext
    providers:
        user_provider:
            id: user_provider
#            entity:
#                class: UserBundle:User
#                property: username
    firewalls:
        main:
            pattern: ^/
            provider: user_provider
            http_basic: ~
            stateless: true
            switch_user_stateless: true

doctrine:
    dbal:
        driver: pdo_sqlite
        path: %kernel.cache_dir%/db.sqlite
        charset: UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

dunglas_api:
    title: My Dummy API
    description: This is a test API

services:
    user_provider:
        class: SwitchUserStatelessBundle\Tests\UserBundle\Security\UserProvider
    resource.user:
        parent: api.resource
        arguments: [ SwitchUserStatelessBundle\Tests\UserBundle\Entity\User ]
        calls:
            - method: initNormalizationContext
              arguments: [ { groups: [ default_output ] } ]
            - method: initDenormalizationContext
              arguments: [ { groups: [ default_input ] } ]
        tags: [ { name: api.resource } ]
