security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: ROLE_ALLOWED_TO_SWITCH
                    john.doe:
                        password: john.doe
                        roles: ROLE_USER
    firewalls:
        main:
            pattern: ^/
            stateless: true
            switch_user_stateless: true
            http_basic: ~
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

framework:
    secret: SwitchUserStatelessBundle
    router:
        resource: %kernel.root_dir%/routing_%kernel.environment%.yml
        strict_requirements: %kernel.debug%
    validation:
        enable_annotations: true
    serializer:
        enable_annotations: true
    trusted_proxies: ~
    test: ~
    session:
        storage_id: session.storage.mock_file
